/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz;

import Modelo.Cotizacion;
import Modelo.ListaCotizaciones;
import Modelo.ListaServicios;
import Modelo.Servicio;
import javax.swing.JOptionPane;

/**
 *
 * @author ONYX
 */
public class FrmAgregarCotizacion extends javax.swing.JInternalFrame {
    ListaServicios listaServicios;
    ListaCotizaciones listaCotizaciones = new ListaCotizaciones();

    /**
     * Creates new form FrmAgregarCotizacion
     */
    public FrmAgregarCotizacion() {
        initComponents();
    }

    public FrmAgregarCotizacion(ListaCotizaciones listaCotizaciones, ListaServicios listaServicios) {
        initComponents();
        this.listaCotizaciones = listaCotizaciones;
        this.listaServicios = listaServicios;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtIDServ = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaC = new javax.swing.JTextField();
        btnAgregarC = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpDetalles = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtNunidades = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);

        jLabel3.setText("ID del servicio:");

        txtIDServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDServActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha Cotizacion:");

        jLabel2.setText("Cantidad de servicios:");

        btnAgregarC.setText("Agregar");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        txpDetalles.setEditable(false);
        txpDetalles.setColumns(20);
        txpDetalles.setRows(5);
        jScrollPane1.setViewportView(txpDetalles);

        jLabel4.setText("Numero de unidades del servicio:");

        txtNunidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNunidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNunidades, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDServ)
                            .addComponent(txtFechaC, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtCantidad)
                            .addComponent(btnAgregarC, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIDServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNunidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarC)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDServActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIDServActionPerformed

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        // TODO add your handling code here:
            if(txtFechaC.getText().equals("") || (txtCantidad.getText().equals(""))){
            javax.swing.JOptionPane.showMessageDialog(this,"Debe de llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                String f = txtFechaC.getText();
                int c = Integer.parseInt(txtCantidad.getText());
                int idS = Integer.parseInt(txtIDServ.getText());
                int uni = Integer.parseInt(txtNunidades.getText());
                
                Servicio objetoEncontrado = listaServicios.buscarServicioID(idS);
                
                if (objetoEncontrado != null) {
                    JOptionPane.showInternalMessageDialog(rootPane, "Servicio encontrado");
                    
                    Cotizacion cotizacion = new Cotizacion(0, f);
                    
                    for (int i = 1; i <= c; i++) {
                        Servicio servicio = null;
                        while (servicio == null) {
                            servicio = listaServicios.buscarServicioID(idS);
                            if (servicio != null) {
                                cotizacion.servicios.agregarServicio(servicio, uni);
                                String mostrar = servicio.mostrar();
                            } else {
                                JOptionPane.showInternalMessageDialog(rootPane, "Servicio no encontrado. Por favor, ingrese un ID válido.");
                            }
                            double total = cotizacion.calcularTotalconIVA();
                            String resultado = listaCotizaciones.agregarCotizacion(cotizacion);
                            String folio = "El folio de la cotización es: " + cotizacion.getFolio();
                            String mostrar = servicio.mostrar();
                            
                            txpDetalles.setText(resultado + "\n" + folio + "\n" + "El costo total es: " + total + "\n" + "\n" + mostrar);
                        }
                    }
                }else {
                     javax.swing.JOptionPane.showMessageDialog(this, "El servicio no fue encontrado", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }
        
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtNunidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNunidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNunidadesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txpDetalles;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFechaC;
    private javax.swing.JTextField txtIDServ;
    private javax.swing.JTextField txtNunidades;
    // End of variables declaration//GEN-END:variables
}
