/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import Modelo.ListaCotizaciones;
import Modelo.ListaServicios;

/**
 *
 * @author ONYX
 */
public class FrmPrincipal extends javax.swing.JFrame {
    public static ListaServicios listaServicios = new ListaServicios(5);
    public static ListaCotizaciones listaCotizaciones = new ListaCotizaciones();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocation(350, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        optVerServicios = new javax.swing.JMenuItem();
        optAgregarServicio = new javax.swing.JMenuItem();
        optMostrarCotizaciones = new javax.swing.JMenu();
        optAddCotizacion = new javax.swing.JMenuItem();
        optBuscarF = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jMenu1.setText("Servicio");

        optVerServicios.setText("Ver servicios");
        optVerServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optVerServiciosActionPerformed(evt);
            }
        });
        jMenu1.add(optVerServicios);

        optAgregarServicio.setText("Agregar Servicio");
        optAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAgregarServicioActionPerformed(evt);
            }
        });
        jMenu1.add(optAgregarServicio);

        jMenuBar1.add(jMenu1);

        optMostrarCotizaciones.setText("Cotizacion");
        optMostrarCotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMostrarCotizacionesActionPerformed(evt);
            }
        });

        optAddCotizacion.setText("Agregar cotizacion");
        optAddCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAddCotizacionActionPerformed(evt);
            }
        });
        optMostrarCotizaciones.add(optAddCotizacion);

        optBuscarF.setText("Buscar cotizacion por folio");
        optBuscarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBuscarFActionPerformed(evt);
            }
        });
        optMostrarCotizaciones.add(optBuscarF);

        jMenuItem1.setText("Mostrar cotizaciones por fecha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        optMostrarCotizaciones.add(jMenuItem1);

        jMenuBar1.add(optMostrarCotizaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optVerServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optVerServiciosActionPerformed
        // TODO add your handling code here:
        FrmMostrarServicios show= new FrmMostrarServicios(listaServicios);
        jDesktopPane1.add(show);
        show.setVisible(true);

    }//GEN-LAST:event_optVerServiciosActionPerformed

    private void optAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAgregarServicioActionPerformed
        // TODO add your handling code here:
        FrmAgregarServicio addS= new FrmAgregarServicio(listaServicios);
        jDesktopPane1.add(addS);
        addS.setVisible(true);

    }//GEN-LAST:event_optAgregarServicioActionPerformed

    private void optAddCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAddCotizacionActionPerformed
        // TODO add your handling code here:
        FrmAgregarCotizacion addC= new FrmAgregarCotizacion(listaCotizaciones, listaServicios);
        jDesktopPane1.add(addC);
        addC.setVisible(true);
    }//GEN-LAST:event_optAddCotizacionActionPerformed

    private void optBuscarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBuscarFActionPerformed
        // TODO add your handling code here:
        FrmBuscarCotizacion busqueda = new FrmBuscarCotizacion(listaCotizaciones);
        jDesktopPane1.add(busqueda);
        busqueda.setVisible(true);
    }//GEN-LAST:event_optBuscarFActionPerformed

    private void optMostrarCotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMostrarCotizacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMostrarCotizacionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmMostrarCotizaciones showC = new FrmMostrarCotizaciones(listaCotizaciones);
        jDesktopPane1.add(showC);
        showC.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem optAddCotizacion;
    private javax.swing.JMenuItem optAgregarServicio;
    private javax.swing.JMenuItem optBuscarF;
    private javax.swing.JMenu optMostrarCotizaciones;
    private javax.swing.JMenuItem optVerServicios;
    // End of variables declaration//GEN-END:variables
}
